### ISSUE TITLE
Create models needed from the database schema

### ISSUE THREAD

**Issue by Miaouw17** [HE-Arc/Versus-Finder#5]

**Comment by Ishydo** [comment]
Pour peupler votre DB une fois que les modèles seront prêts:

[https://www.smashbros.com/assets_v2/data/fighter.json](https://www.smashbros.com/assets_v2/data/fighter.json)

Vous y trouverez aussi la liste des titres musicaux et d'autres trucs mais pas sûr que ça soit très utile.

Source: https://www.reddit.com/r/smashbros/comments/9p2egc/hidden_json_files_on_smash_ultimate_site/

**Comment by Miaouw17** [comment]
Merci ! ça nous évitera de tous rentrer à la main 😃 

Sinon je viens de push les modèles et la migrations. 
Ne pas oublier de :
python manage.py migrate

il y aura peut être des modifications à faire si django n'est pas aussi implicite que je le pense..

**Comment by Miaouw17** [comment]
J'ai fais la fixture pour les fighters, un script permet de le faire automatiquement mais y'a 1-2 p'tit problèmes d'encodage et de <br > qui traine, donc j'ai corrigé à la main car pas trop envie de perdre du temps la dessus 😺

**Comment by Miaouw17** [comment]
J'ai update les models pour qu'ils soient correct, il y avait des choses auxquelles je n'avais pas pensé tout de suite comme les DateTimeField() avec datetime.now() et il y avait des petites modifs au niveau de la logique 

En plus de cela, j'ai fais un peu plus de fixture histoire de pouvoir tester un peu le fonctionnement et la logique de l'app

**Comment by Miaouw17** [comment]
Les models sont actuellement pas trop mal, il risque d'y avoir des petites modifications et ajustements mais dans la logique ils sont faits
