### ISSUE TITLE
Create and test calendar for the schedule of a user

### ISSUE THREAD

**Issue by Miaouw17** [HE-Arc/Versus-Finder#6]
outils pour faire un calendrier ;
https://github.com/llazzaro/django-scheduler
https://django-story.readthedocs.io/en/latest/src/014.tp.agenda.templates.html
https://djangopackages.org/grids/g/calendar/

**Comment by crypt0log-hai** [comment]
- [x] Ajout d'un calendrier
- [x] Repertorier les matchs du joueur
- [x] Faire un lien clickable

Outil utilisé :
https://fullcalendar.io/docs

**Comment by crypt0log-hai** [comment]
The user can delete his timetable.
