### ISSUE TITLE
Create navbar/sidebar 

### ISSUE THREAD

**Issue by Miaouw17** [HE-Arc/Versus-Finder#7]
Ajouter une bar de navigation soit au top soit sur le côté gauche de la page afin de pouvoir placer les liens nécessaire à la navigation dans le site

**Comment by crypt0log-hai** [comment]
- [x] Création de la navbar avec les liens
- [x] (optionnel) mise en place en sidebar

**Comment by crypt0log-hai** [comment]
@Maering  à refait en sidebar
